/*Registros de los permisos*/
use scliz;

insert into permiso(codigoPermiso, nombrePermiso, estadoPermiso)
values
	("RegistrarGerente", upper("Registrar Gerente"), "ACTIVO"),
    ("ModificarGerente", upper("Modificar Gerente"), "ACTIVO"),
    ("ConsultarGerente", upper("Consultar Gerente"), "ACTIVO"),
    ("RegistrarUsuario", upper("Registrar Usuario"), "ACTIVO"),
    ("ConsultarUsuario", upper("Consultar Usuario"), "ACTIVO"),
    ("ModificarContraseina", upper("Modificar Contraseña"), "ACTIVO"),
    ("RegistrarEmpleado", upper("Registrar Empleado"), "ACTIVO"),
    ("ListarEmpleado", upper("Listar Empleados"), "ACTIVO"),
    ("ConsultarEmpleado", upper("Consultar Empleado"), "ACTIVO"),
    ("ModificarEmpleado", upper("Modificar Empleado"), "ACTIVO"),
    ("ModificarEmpleadoCuenta", upper("Modificar Empleado Cuenta"), "ACTIVO"),
    ("RegistrarRol", upper("Registrar Rol"), "ACTIVO"),
    ("ModificarRol", upper("Modificar Rol"), "ACTIVO"),
    ("ListarRol", upper("Listar Roles"), "ACTIVO"),
    ("ConsultarRol", upper("Consultar Rol"), "ACTIVO"),
    ("RegistrarFactura", upper("Registrar Factura"), "ACTIVO"),
    ("ListarFactura", upper("Listar Facturas"), "ACTIVO"),
    ("ConsultarFactura", upper("Consultar Factura"), "ACTIVO"),
    ("CalcularValorTotalFactura", upper("Calcular Valor Total Factura"), "ACTIVO"),
    ("RegistrarCliente", upper("Registrar Cliente"), "ACTIVO"),
    ("ListarCliente", upper("Listar Clientes"), "ACTIVO"),
    ("ModificarCliente", upper("Modificar Cliente"), "ACTIVO"),
    ("ConsultarCliente", upper("Consultar Cliente"), "ACTIVO"),
    ("Registrar Proveedor", upper("Registrar Proveedor"), "ACTIVO"),
    ("ListarProveedor", upper("Listar Proveedores"), "ACTIVO"),
    ("ModificarProveedor", upper("Modificar Proveedor"), "ACTIVO"),
    ("ConsultarProveedor", upper("Consultar Proveedor"), "ACTIVO"),
    ("RegistrarPedido", upper("Registrar Pedido"), "ACTIVO"),
    ("ModificarPedido", upper("Modificar Pedido"), "ACTIVO"),
    ("ConsultarPedido", upper("Consultar Pedido"), "ACTIVO"),
    ("ListarPedido", upper("Listar Pedidos"), "ACTIVO"),
    ("CalcularValorTotalPedido", upper("Calcular Valor Total Pedido"), "ACTIVO"),
    ("RegistrarDetallePedido", upper("Registrar Detalle Pedido"), "ACTIVO"),
    ("ModificarDetallePedido", upper("Modificar Detalle Pedido"), "ACTIVO"),
    ("EliminarDetallePedido", upper("Eliminar Detalle Pedido"), "ACTIVO"),
    ("ConsultarDetallePedido", upper("Consultar Detalle Pedido"), "ACTIVO"),
    ("CalcularValorUnitarioDetallePedido", upper("Calcular Valor Unitario Detalle Pedido"), "ACTIVO"),
    ("CalcularValorGananciaDetallePedido", upper("Calcular Valor Ganancia Detalle Pedido"), "ACTIVO"),
    ("RegistrarRolPermiso", upper("Registrar Rol Permiso"), "ACTIVO"),
    ("ModificarRolPermiso", upper("Modificar Rol Permiso"), "ACTIVO"),
    ("ConsultarRolPermiso", upper("Consultar Rol Permiso"), "ACTIVO"),
    ("ListarRolPermiso", upper("Listar Roles Y Permisos"), "ACTIVO"),
    ("ListarPermiso", upper("Listar Permisos"), "ACTIVO"),
    ("ConsultarPermiso", upper("Consultar Permiso"), "ACTIVO"),
    ("ModificarPermiso", upper("Modificar Permiso"), "ACTIVO"),
    ("RegistrarDetalleFactura", upper("Registrar Detalle Factura"), "ACTIVO"),
    ("ModificarDetalleFactura", upper("Modificar Detalle Factura"), "ACTIVO"),
    ("EliminarDetalleFactura", upper("Eliminar Detalle Factura"), "ACTIVO"),
    ("ConsultarDetalleFactura", upper("Consultar Detalle Factura"), "ACTIVO"),
    ("CalcularValorDetalleFactura", upper("Calcular Valor Detalle Factura"), "ACTIVO"),
    ("RegistrarProducto", upper("Registrar Producto"), "ACTIVO"),
    ("ModificarProducto", upper("Modificar Producto"), "ACTIVO"),
    ("ConsultarProducto", upper("Consultar Producto"), "ACTIVO"),
    ("CalcularValorProductoIVA", upper("Calcular Valor Producto IVA"), "ACTIVO"),
    ("ListarNombreProducto", upper("Listar Nombre Producto"), "ACTIVO"),
    ("ListarDescripcionProducto", upper("Listar DescripcionProducto"), "ACTIVO"),
    ("ListarMarcaProducto", upper("Listar Marca Producto"), "ACTIVO"),
    ("ListarIVA", upper("Listar IVA"), "ACTIVO"),
    ("RegistrarDetalleInventario", upper("Registrar Detalle Inventario"), "ACTIVO"),
    ("RegistrarInventario", upper("Registrar Inventario"), "ACTIVO"),
    ("ModificarInventario", upper("Modificar Inventario"), "ACTIVO"),
    ("ListarInventario", upper("Listar Inventario"), "ACTIVO"),
    ("ConsultarInventario", upper("Consultar Inventario"), "ACTIVO");